version: 2.1

jobs:
  build: 
    machine:
      image: ubuntu-2004:202010-01
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - run:
          name: Test
          command: docker --context default build --progress plain --target test .

      - run:
          name: Build
          command: docker --context default build --progress plain --target app --tag latest .
