version: 2.1

jobs:
  build: 
    machine:
      image: ubuntu-2004:202010-01
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - run:
          name: Test
          command: docker --context default build --progress plain --target test .

      - run:
          name: Build
          command: docker --context default build --progress plain --target app --tag docker.pkg.github.com/cromwellryan/cci-test-build/app:latest .

      - run:
          name: Log in to Github Container Registry
          command: |
            docker login https://docker.pkg.github.com -u $GH_REGISTRY_USER -p $GH_REGISTRY_PASS 

      - run:
          name: Push Image
          command: |
            docker push docker.pkg.github.com/cromwellryan/cci-test-build/app:latest
